Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'Providers/HistoricalProviders.psm1') -Force

function Get-MmtlHistoricalLoaderAvailability {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$MinecraftId,[Parameter(Mandatory)]$Catalog,[Parameter(Mandatory)][string]$RuntimeRoot,[switch]$Offline,[scriptblock]$HttpGet)
    $result=[Collections.Generic.List[object]]::new()
    $legacy=Get-MmtlLegacyFabricProviderSnapshot -RuntimeRoot $RuntimeRoot -Offline:$Offline -HttpGet $HttpGet
    $legacyOk=@($legacy.supportedVersions|Where-Object version -CEQ $MinecraftId).Count -gt 0
    $result.Add([pscustomobject]@{loaderId='LegacyFabric';availability=if($legacyOk){'Available'}elseif($legacy.providerStatus -in @('Available','Stale')){'Unavailable'}else{'Unknown'};providerStatus=$legacy.providerStatus;sourceClass='ActiveOfficial';trustClass='TrustedOfficial';transportSecurity='HTTPS';maintenanceState='Active';cacheStatus=$legacy.cacheStatus;source=$legacy.sourceUrl;candidateCount=if($legacyOk){@(Get-MmtlLegacyFabricCandidates -MinecraftId $MinecraftId -RuntimeRoot $RuntimeRoot -Offline:$Offline -HttpGet $HttpGet).Count}else{0};notes=@($legacy.error)})
    $ornithe=Get-MmtlOrnitheProviderSnapshot -RuntimeRoot $RuntimeRoot -Offline:$Offline -HttpGet $HttpGet
    $ornitheOk=@($ornithe.supportedVersions|Where-Object version -CEQ $MinecraftId).Count -gt 0
    $result.Add([pscustomobject]@{loaderId='OrnitheLoader';availability=if($ornitheOk){'Available'}elseif($ornithe.providerStatus -in @('Available','Stale')){'Unavailable'}else{'Unknown'};providerStatus=$ornithe.providerStatus;sourceClass='ActiveOfficial';trustClass='TrustedOfficial';transportSecurity='HTTPS';maintenanceState='Active';cacheStatus=$ornithe.cacheStatus;source=$ornithe.sourceUrl;candidateCount=if($ornitheOk){@(Get-MmtlOrnitheCandidates -MinecraftId $MinecraftId -RuntimeRoot $RuntimeRoot -Offline:$Offline -HttpGet $HttpGet).Count}else{0};notes=@($ornithe.error)})
    $lite=Get-MmtlLiteLoaderProviderSnapshot -RuntimeRoot $RuntimeRoot -Offline:$Offline -HttpGet $HttpGet
    $liteCandidates=@(Get-MmtlLiteLoaderCandidates -MinecraftId $MinecraftId -Snapshot $lite)
    $result.Add([pscustomobject]@{loaderId='LiteLoader';availability=if($liteCandidates.Count){'Available'}elseif($lite.providerStatus -in @('Available','Stale')){'Unavailable'}else{'Unknown'};providerStatus=$lite.providerStatus;sourceClass='HistoricalOfficial';trustClass='VerifiedHistorical';transportSecurity='HTTPS';maintenanceState='Archived';cacheStatus=$lite.cacheStatus;source=$lite.sourceUrl;candidateCount=$liteCandidates.Count;notes=@($lite.error)})
    foreach($loader in @('Rift','ModLoader','ModLoaderMP')){
        $items=switch($loader){'Rift'{@(Get-MmtlRiftCandidates -MinecraftId $MinecraftId)}'ModLoader'{@(Get-MmtlModLoaderArchiveCandidates -MinecraftId $MinecraftId)}'ModLoaderMP'{@(Get-MmtlModLoaderMPArchiveCandidates -MinecraftId $MinecraftId)}}
        $result.Add([pscustomobject]@{loaderId=$loader;availability=if($items.Count){'Available'}else{'Unavailable'};providerStatus=if($items.Count){'CuratedArchive'}else{'NotCatalogued'};sourceClass=if($loader -eq 'Rift'){'HistoricalOfficial'}else{'VerifiedCommunityArchive'};trustClass='VerifiedHistorical';transportSecurity=if($loader -eq 'Rift'){'ArchivedSnapshot'}else{'ArchivedSnapshot'};maintenanceState='Archived';cacheStatus='Curated';source=if($loader -eq 'Rift'){'https://github.com/DimensionalDevelopment/Rift'}else{'https://mcarchive.net/mods/'+$loader.ToLowerInvariant()};candidateCount=$items.Count;notes=@()})
    }
    $result.Add([pscustomobject]@{loaderId='JarMod';availability='Manual';providerStatus='ManualOnly';sourceClass='ManualArtifact';trustClass='UnverifiedHistorical';transportSecurity='LocalManual';maintenanceState='Unknown';cacheStatus='NotApplicable';source=$null;candidateCount=0;notes=@('Requires a user-supplied local artifact; no catalog availability is inferred.')})
    [pscustomobject][ordered]@{schemaVersion=1;minecraftId=$MinecraftId;scope='Historical';entries=@($result);generatedAt=[DateTimeOffset]::UtcNow.ToString('o')}
}

function Get-MmtlHistoricalProviderStatus {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$LoaderId,[Parameter(Mandatory)]$Catalog,[Parameter(Mandatory)][string]$RuntimeRoot,[switch]$Offline)
    if($LoaderId -eq 'LegacyFabric'){$snapshot=Get-MmtlLegacyFabricProviderSnapshot -RuntimeRoot $RuntimeRoot -Offline:$Offline;$coverage=Get-MmtlLegacyFabricReleaseCoverage -Catalog $Catalog -Snapshot $snapshot;return [pscustomobject]@{loaderId=$LoaderId;providerStatus=$snapshot.providerStatus;cacheStatus=$snapshot.cacheStatus;sourceClass='ActiveOfficial';trustClass='TrustedOfficial';maintenanceState='Active';transportSecurity='HTTPS';releaseCoverage=$coverage;provenance=$snapshot.provenance;error=$snapshot.error}}
    if($LoaderId -eq 'OrnitheLoader'){$snapshot=Get-MmtlOrnitheProviderSnapshot -RuntimeRoot $RuntimeRoot -Offline:$Offline;$coverage=Get-MmtlOrnitheReleaseCoverage -Catalog $Catalog -Snapshot $snapshot;return [pscustomobject]@{loaderId=$LoaderId;providerStatus=$snapshot.providerStatus;cacheStatus=$snapshot.cacheStatus;sourceClass='ActiveOfficial';trustClass='TrustedOfficial';maintenanceState='Active';transportSecurity='HTTPS';releaseCoverage=$coverage;provenance=$snapshot.provenance;error=$snapshot.error}}
    if($LoaderId -eq 'LiteLoader'){$snapshot=Get-MmtlLiteLoaderProviderSnapshot -RuntimeRoot $RuntimeRoot -Offline:$Offline;$releaseIds=@($Catalog.entries|Where-Object{$_.type -eq 'release' -and $_.id -cin @($snapshot.supportedVersions)}|ForEach-Object id);return [pscustomobject]@{loaderId=$LoaderId;providerStatus=$snapshot.providerStatus;cacheStatus=$snapshot.cacheStatus;sourceClass='HistoricalOfficial';trustClass='VerifiedHistorical';maintenanceState='Archived';transportSecurity='HTTPS';releaseCoverage=[pscustomobject]@{releaseCount=$releaseIds.Count;releaseIds=$releaseIds};provenance=$snapshot.provenance;error=$snapshot.error}}
    if($LoaderId -eq 'Rift'){$items=@(Get-MmtlRiftCandidates -MinecraftId '1.13')+@(Get-MmtlRiftCandidates -MinecraftId '1.13.2');return [pscustomobject]@{loaderId=$LoaderId;providerStatus='CuratedArchive';cacheStatus='Curated';sourceClass='HistoricalOfficial';trustClass='VerifiedHistorical';maintenanceState='Archived';transportSecurity='ArchivedSnapshot';releaseCoverage=[pscustomobject]@{releaseCount=$items.Count;releaseIds=@($items|ForEach-Object minecraftId|Select-Object -Unique)};provenance=@($items|ForEach-Object provenance);error=$null}}
    if($LoaderId -in @('ModLoader','ModLoaderMP')){$ids=if($LoaderId -eq 'ModLoader'){@('1.0','1.2.5','1.4.7')}else{@('1.2.5','1.3.2')};$items=@(foreach($mc in $ids){if($LoaderId -eq 'ModLoader'){Get-MmtlModLoaderArchiveCandidates -MinecraftId $mc}else{Get-MmtlModLoaderMPArchiveCandidates -MinecraftId $mc}});return [pscustomobject]@{loaderId=$LoaderId;providerStatus='CuratedArchive';cacheStatus='Curated';sourceClass='VerifiedCommunityArchive';trustClass='VerifiedHistorical';maintenanceState='Archived';transportSecurity='ArchivedSnapshot';releaseCoverage=[pscustomobject]@{releaseCount=@($items|Select-Object -ExpandProperty minecraftId -Unique).Count;releaseIds=@($items|ForEach-Object minecraftId|Select-Object -Unique)};provenance=@($items|ForEach-Object source);error=$null}}
    if($LoaderId -eq 'JarMod'){return [pscustomobject]@{loaderId=$LoaderId;providerStatus='ManualOnly';cacheStatus='NotApplicable';sourceClass='ManualArtifact';trustClass='UnverifiedHistorical';maintenanceState='Unknown';transportSecurity='LocalManual';releaseCoverage=[pscustomobject]@{releaseCount=0;releaseIds=@()};provenance=@();error='Requires user-supplied artifact.'}}
    throw "Unknown historical provider identity: $LoaderId"
}
Export-ModuleMember -Function Get-MmtlHistoricalLoaderAvailability,Get-MmtlHistoricalProviderStatus
